name: papyrus
description: "Digital library management application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  collection: ^1.19.1
  provider: ^6.1.5+1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  google_sign_in: ^7.2.0
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.69.0
  intl: ^0.19.0
  http: ^1.2.0
  file_picker: ^8.0.0+1
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  epub_pro: ^5.6.0
  syncfusion_flutter_pdf: ^32.2.3
  dart_mobi: ^1.0.2
  archive: ^4.0.7
  unrar_file: ^1.1.0
  xml: ^6.6.1
  image: ^4.7.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_logo.png
    - assets/images/logo.png
    - assets/images/logo-icon-light.svg
    - assets/images/logo-icon-dark.svg
    - assets/images/book_placeholder.jpg
    - assets/images/book_placeholder_2.jpg
    - assets/images/profile.png
    - assets/images/auth-illustration.png

  fonts:
    - family: MadimiOne
      fonts:
        - asset: fonts/MadimiOne-Regular.ttf